// Embeds the pre-built reading data into index.html, between two marker comments, so the app never
// has to ask Dicta or guess a transliteration while someone reads.
//
//   node tools/build-nikud.mjs     (once, or when story text changes)  -> tools/nikud-cache.json
//   node tools/apply-data.mjs                                           -> rewrites the block in index.html
//
// Inputs:  tools/nikud-cache.json        vowelled paragraphs, key "<storyId>|<page>:<paragraph>"
//          tools/nikud-overrides.json    hand fixes, key "<storyId>|<page>:<paragraph>:<word index>" -> vowelled token
//          tools/translit-overrides.json hand fixes for transliteration, key vowelled word -> latin
//          tools/glosses.json            short English meaning per vowelled word (shared by all stories)
//          tools/vocab-fixes.json        vocabulary corrections, each tagged with its story
// Output block (inside the storiesData script, after all the stories are defined):
//   STORY_NIKUD, STORY_TRANSLIT, STORY_GLOSS, VOCAB_FIXES (+ the code that applies them)
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { translit } from './translit.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const read = (f, d) => (fs.existsSync(path.join(here, f)) ? JSON.parse(fs.readFileSync(path.join(here, f), 'utf8')) : d)
const cache = read('nikud-cache.json', {})
const fixes = read('nikud-overrides.json', {})
const tov = read('translit-overrides.json', {})
const gloss = read('glosses.json', {})
const vfix = read('vocab-fixes.json', { forms: [], replace: [], move: [], remove: [] })
const PUNCT = /[,.!?;:"'״׳()\[\]{}…“”–—]/g

const nikud = {}
for (const [key, para] of Object.entries(cache)) {
  const words = para.split(/\s+/)
  words.forEach((w, n) => { const fx = fixes[key + ':' + n]; if (fx) words[n] = fx })
  nikud[key] = words.join(' ')
}
const table = {}
for (const para of Object.values(nikud)) for (const w of para.split(/\s+/)) {
  const f = w.replace(PUNCT, '')
  if (f && !table[f]) table[f] = translit(f, tov)
}

const block = `// <<STORY_NIKUD>> generated by tools/apply-data.mjs - do not edit by hand
const STORY_NIKUD = ${JSON.stringify(nikud)};
const STORY_TRANSLIT = ${JSON.stringify(table)};
// Short in-context English meaning for every word (tools/glosses/*.txt), keyed by the NFC-normalised vowelled word.
const STORY_GLOSS = ${JSON.stringify(gloss)};

// Vocabulary corrections (tools/build-vocab-fixes.mjs): inflected forms as written on each page, entries that
// named the wrong word, a word used on a different page, a word not in the story. Applied once, at load.
const VOCAB_FIXES = ${JSON.stringify(vfix)};
(function applyVocabFixes() {
  const story = (id) => STORIES.find((s) => s.id === (id || 'apartment'));
  const find = (pages, p, he) => (pages[p].vocab || []).findIndex((v) => v.he === he);
  VOCAB_FIXES.replace.forEach((r) => { const pg = story(r.story).pages; const i = find(pg, r.page, r.he); if (i >= 0) pg[r.page].vocab[i] = Object.assign({}, r.with); });
  VOCAB_FIXES.remove.forEach((r) => { const pg = story(r.story).pages; const i = find(pg, r.page, r.he); if (i >= 0) pg[r.page].vocab.splice(i, 1); });
  VOCAB_FIXES.move.forEach((m) => { const pg = story(m.story).pages; const i = find(pg, m.from, m.he); if (i >= 0) { const v = pg[m.from].vocab.splice(i, 1)[0]; pg[m.to].vocab = pg[m.to].vocab || []; if (find(pg, m.to, m.he) < 0) pg[m.to].vocab.push(v); } });
  VOCAB_FIXES.forms.forEach((f) => { const pg = story(f.story).pages; const i = find(pg, f.page, f.he); if (i >= 0) pg[f.page].vocab[i].forms = f.forms; });
})();
// <<END STORY_NIKUD>>`

const file = path.join(here, '..', 'index.html')
let html = fs.readFileSync(file, 'utf8')
const mark = /\/\/ <<STORY_NIKUD>>[\s\S]*?\/\/ <<END STORY_NIKUD>>/
// The block goes right after the LAST story is registered (STORIES.push(...)), because the vocab fixes look
// stories up by id. Remove any earlier copy first, then insert after the last push.
html = html.replace(mark, '')
const lastPush = html.lastIndexOf('STORIES.push(')
if (lastPush < 0) throw new Error('no STORIES.push found in index.html')
const semi = html.indexOf(';', lastPush)
html = html.slice(0, semi + 1) + '\n\n' + block + html.slice(semi + 1)
fs.writeFileSync(file, html)
console.log('vocab fixes:', vfix.forms.length + ' forms, ' + vfix.replace.length + ' replaced, ' + vfix.move.length + ' moved, ' + vfix.remove.length + ' removed')
console.log('paragraphs', Object.keys(nikud).length, '| transliteration entries', Object.keys(table).length, '| glosses', Object.keys(gloss).length, '| hand fixes applied', Object.keys(fixes).length)
