// Embeds the pre-built reading data into index.html, between two marker comments, so the app never
// has to ask Dicta or guess a transliteration while someone reads.
//
//   node tools/build-nikud.mjs     (once, or when the story text changes)  -> tools/nikud-cache.json
//   node tools/apply-data.mjs                                               -> writes the block into index.html
//
// Inputs:  tools/nikud-cache.json        vowelled paragraphs, key "<page>:<paragraph>"
//          tools/nikud-overrides.json    hand fixes, key "<page>:<paragraph>:<word index>" -> vowelled word
//          tools/translit-overrides.json hand fixes for transliteration, key vowelled word -> latin
// Output block (inside the storiesData script, right after STORIES):
//   const STORY_NIKUD   = { "<page>:<paragraph>": "vowelled paragraph" }
//   const STORY_TRANSLIT = { "<vowelled word without punctuation>": "latin" }
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { translit } from './translit.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const read = (f, d) => (fs.existsSync(path.join(here, f)) ? JSON.parse(fs.readFileSync(path.join(here, f), 'utf8')) : d)
const cache = read('nikud-cache.json', {})
const fixes = read('nikud-overrides.json', {})
const tov = read('translit-overrides.json', {})
const PUNCT = /[,.!?;:"'״׳()\[\]{}…“”–—]/g

const nikud = {}
for (const [key, para] of Object.entries(cache)) {
  const words = para.split(/\s+/)
  words.forEach((w, n) => { const fx = fixes[key + ':' + n]; if (fx) words[n] = fx })
  nikud[key] = words.join(' ')
}
const table = {}
for (const para of Object.values(nikud)) for (const w of para.split(/\s+/)) {
  const f = w.replace(PUNCT, '')
  if (f && !table[f]) table[f] = translit(f, tov)
}

const block = `// <<STORY_NIKUD>> generated by tools/apply-data.mjs - do not edit by hand
const STORY_NIKUD = ${JSON.stringify(nikud)};
const STORY_TRANSLIT = ${JSON.stringify(table)};
// <<END STORY_NIKUD>>`

const file = path.join(here, '..', 'index.html')
let html = fs.readFileSync(file, 'utf8')
const mark = /\/\/ <<STORY_NIKUD>>[\s\S]*?\/\/ <<END STORY_NIKUD>>/
if (mark.test(html)) html = html.replace(mark, () => block)
else {
  // first run: place it straight after the STORIES array (string-aware bracket match)
  const sIdx = html.indexOf('const STORIES = [')
  let i = html.indexOf('[', sIdx), depth = 0, q = null, esc = false
  for (; i < html.length; i++) {
    const c = html[i]
    if (q) { if (esc) esc = false; else if (c === '\\') esc = true; else if (c === q) q = null; continue }
    if (c === '"' || c === "'" || c === '`') { q = c; continue }
    if (c === '/' && html[i + 1] === '/') { while (html[i] !== '\n' && i < html.length) i++; continue }
    if (c === '[') depth++
    else if (c === ']') { depth--; if (depth === 0) break }
  }
  const semi = html.indexOf(';', i)
  html = html.slice(0, semi + 1) + '\n\n' + block + html.slice(semi + 1)
}
fs.writeFileSync(file, html)
console.log('paragraphs', Object.keys(nikud).length, '| transliteration entries', Object.keys(table).length, '| hand fixes applied', Object.keys(fixes).length)
